### ISSUE TITLE
Definir Casos de Uso

### ISSUE THREAD

**Issue by Ivolatile-0** [AndreLuizJPoles/GUIATURISTICO#13]
https://lucid.app/lucidchart/7e5d4a5b-7d8f-460a-9f3d-a2c47970a416/edit?page=.Q4MUjXso07N&invitationId=inv_3d3e5d8b-5157-44f1-86a1-c8db38f549fd#

**Comment by AndreLuizJPoles** [comment]
Adicionar ADM do sistema como ator,  gerenciar cupons (caso de uso) e controle de assinatura (caso de uso)

**Comment by AndreLuizJPoles** [comment]
Assim q a gente terminar as construções das telas, por favor revisar os casos de uso.
