### ISSUE TITLE
Modelo Conceitual

### ISSUE THREAD

**Issue by AndreLuizJPoles** [AndreLuizJPoles/GUIATURISTICO#16]
https://lucid.app/lucidchart/d38caa9a-6ee6-47dc-b400-dd89c98db3d1/edit?beaconFlowId=9E268D0CBE39F85C&invitationId=inv_d836213e-db56-4164-83c2-1d32c7cd8e8e&page=0_0#

**Comment by RarissaCorrea** [comment]
Discutir melhor sobre Classe Favoritos.
