### ISSUE TITLE
Lista de Requisitos (Documento de Concepção)

### ISSUE THREAD

**Issue by AndreLuizJPoles** [AndreLuizJPoles/GUIATURISTICO#21]
https://fatecspgov-my.sharepoint.com/:w:/g/personal/andre_poles_fatec_sp_gov_br/EWhZwXkGHWxHmmHVGyxFa1gBpzzSbIPkhIlsQ2ggKfG6DQ?e=bBaJue

**Comment by RarissaCorrea** [comment]
- [ ] Fazer os Requisitos não funcionais de cada Requisito
