### ISSUE TITLE
Construção da Tela de Perfil

### ISSUE THREAD

**Issue by AndreLuizJPoles** [AndreLuizJPoles/GUIATURISTICO#26]
https://www.figma.com/file/hh1Q2wNZkf8xapL7wQyrxN/Guia-tur%C3%ADstico?node-id=0-1&t=WtfYIKGV8CxCLM9E-0

**Comment by AndreLuizJPoles** [comment]
Incluir as opções do perfil e o formulário para recomendações.

**Comment by joao-ghizzi** [comment]
foi criado os ícones de configuração.
