### ISSUE TITLE
Construção da Tela de Detalhes de um Evento

### ISSUE THREAD

**Issue by AndreLuizJPoles** [AndreLuizJPoles/GUIATURISTICO#6]
https://www.figma.com/file/hh1Q2wNZkf8xapL7wQyrxN/Guia-tur%C3%ADstico?node-id=0-1&t=WtfYIKGV8CxCLM9E-0

**Comment by AndreLuizJPoles** [comment]
Adicionar a distância dos locais, as vantagens de ser assinante, colocar a opção de se inscrever na assinatura e entrada para fazer o comentário.

**Comment by MLenartevitz** [comment]
Feito, Foi inserido nas telas: distância dos locais, as vantagens de ser assinante,  opção de se inscrever na assinatura e entrada para fazer o comentário.
