### ISSUE TITLE
Construção da Tela de Detalhes de um Estabelecimento Comum

### ISSUE THREAD

**Issue by AndreLuizJPoles** [AndreLuizJPoles/GUIATURISTICO#7]
https://www.figma.com/file/hh1Q2wNZkf8xapL7wQyrxN/Guia-tur%C3%ADstico?node-id=0-1&t=WtfYIKGV8CxCLM9E-0

**Comment by MLenartevitz** [comment]
Feio, foi inserido: entrada de comentário, vantagens de ser assinante, forma de acessar a aba de assinatura, dias de funcionamento (seg - sex), formas de entrar em contato com o estabelecimento e distância do local.
